name: execute
description: Execute a remote script
inputs:
  host:
    description: 'SSH hostname'
    required: true
  user:
    description: 'SSH user'
    required: true
  target_path:
    description: 'path to run command from'
    required: true
  target_script:
    description: 'commands to run'
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: ssh ${{ inputs.user }}@${{ inputs.host }} "cd ${{ inputs.target_path }} && ${{ inputs.target_script }}"
