name: execute
description: Execute a remote script
inputs:
  host:
    description: 'SSH hostname'
    required: true
  port:
    description: 'SSH port'
    required: true
    default: '22'
  user:
    description: 'SSH user'
    required: true
  target_path:
    description: 'path to run command from'
    required: true
  commands:
    description: 'commands to run'
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        stdout=$(ssh ssh://${{ inputs.user }}@${{ inputs.host }}:${{ inputs.port }} "cd ${{ inputs.target_path }} && ${{ inputs.commands }}")
        echo "stdout=$$stdout" >> $GITHUB_OUTPUT
