name: checkout
description: Checkout a given revision on a given branch
inputs:
  branch:
    description: Branch to check out
    required: true
  github_sha:
    description: SHA of commit to check out (defaults to latest)
    required: false
runs:
  using: composite
  steps:
    - name: Determine commit SHA
      shell: bash
      run: |
        if [ ! -z "${{ inputs.github_sha }}" ]
        then
          echo "deploy_sha=${{ inputs.github_sha }}" >> $GITHUB_ENV
          echo "fetch_depth=0" >> $GITHUB_ENV
        else
          echo "deploy_sha=${{ github.sha }}" >> $GITHUB_ENV
          echo "fetch_depth=1" >> $GITHUB_ENV
        fi
    - name: Checkout branch ${{ inputs.branch }}
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.branch }}
        fetch-depth: ${{ env.fetch_depth }}
    - name: "Checkout ${{ inputs.branch }} at commit ${{ env.deploy_sha }}"
      shell: bash
      run: |
        git checkout ${{ env.deploy_sha }}
