name: checkout
description: Checkout a given revision on a given branch
inputs:
  branch:
    description: Branch to check out
    required: true
  github_sha:
    description: SHA of commit to check out (defaults to latest)
    required: false
  fetch_depth:
    description: Set fetch-depth 0 to fetch all history for all branches and tags.
    type: number
    required: false
runs:
  using: composite
  steps:
    - name: Checkout branch ${{ inputs.branch }}
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.branch }}
        fetch-depth: ${{ env.fetch_depth }}
    - name: "Checkout ${{ inputs.branch }} at commit ${{ env.deploy_sha }}"
      shell: bash
      run: |
        git checkout ${{ inputs.github_sha }}
