name: transfer
description: Transfer code to the remote
inputs:
  remote_dir:
    description: Path to the directory on the remote to transfer files to
    required: true
  local_dir:
    description: Path to the local directory to transfer files from
    required: false
    default: '.'
  post_transfer_commands:
    description: Commands to execute post-transfer (bash)
    required: false
  ssh_host:
    description: SSH hostname
    required: true
  ssh_port:
    description: SSH port number
    required: false
    default: '22'
  ssh_user:
    description: SSH user
    required: true
  ssh_private_key:
    description: SSH private key
    required: true
  scratch:
    description: Write all paths from scratch
    required: false
  exclude_paths:
    description: Paths to exclude from transfer, as accepted by rsync --exclude
    required: false
  include_paths:
    description: Paths to include in transfer, as accepted by rsync --include
    required: false
runs:
  using: composite
  steps:
    - name: "Create remote directory '${{ inputs.remote_dir }}' if it doesn't exist"
      env:
        COMMANDS: |
          mkdir -p ${{ inputs.remote_dir }}; true
      uses: esign/.github/.github/actions/execute@v2
      with:
        host: ${{ inputs.ssh_host }}
        port: ${{ inputs.ssh_port }}
        user: ${{ inputs.ssh_user }}
        target_path: /
        commands: ${{ env.COMMANDS }}
    - id: compose-rsync-flags
      name: "Compose rsync flags"
      shell: bash
      run: |
        excludes=$(echo "${{ inputs.exclude_paths }}" | sed '1,$s/\r//g' | sed '/^$/d' | sed -r '1,$s/^(.*)$/--exclude \1/' | sed -z '1,$s/\n/ /g' | sed '1,$s/\s$//g')
        includes=$(echo "${{ inputs.include_paths }}" | sed -r '1,$s/^(.+)$/--include \1/' | sed -z '1,$s/\n/ /g')
        flags="$excludes"
        
        if [ ! -z "$includes" ]
        then
          flags="$flags $includes"
        fi

        flags="$flags --include \"*/\""
        
        if [ "${{ inputs.scratch }}" = false ]
        then
          flags="$flags --exclude \"*\""
        fi
        
        echo "flags=$flags" >> $GITHUB_OUTPUT
    - name: "Upload local '${{ inputs.local_dir }}' to remote '${{ inputs.remote_dir }}'"
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -azr --delete ${{ steps.compose-rsync-flags.outputs.flags }}
        path: ${{ inputs.local_dir }}
        remote_path: ${{ inputs.remote_dir }}
        remote_host: ${{ inputs.ssh_host }}
        remote_port: ${{ inputs.ssh_port }}
        remote_user: ${{ inputs.ssh_user }}
        remote_key: ${{ inputs.ssh_private_key }}
    - id: compose-post-transfer-commands
      name: "Compose post transfer commands"
      shell: bash
      run: |
        commands=$(echo "${{ inputs.post_transfer_commands }}" | sed '1,$s/\r//g' | sed '/^$/d' | sed -z '1,$s/\n/ \&\& /g' | sed -r '1,$s/\s\&\&\s?$//g')
        echo "commands=$commands" >> $GITHUB_OUTPUT
    - name: Execute post transfer commands
      uses: esign/.github/.github/actions/execute@v2
      with:
        host: ${{ inputs.ssh_host }}
        port: ${{ inputs.ssh_port }}
        user: ${{ inputs.ssh_user }}
        target_path: ${{ inputs.remote_dir }}
        commands: ${{ steps.compose-post-transfer-commands.outputs.commands }}
