name: transfer
description: Transfer code to the remote
inputs:
  remote_dir:
    description: Path to the directory on the remote to transfer files to
    required: true
  local_dir:
    description: Path to the local directory to transfer files from
    required: false
    default: '.'
  post_transfer_commands:
    description: Commands to execute post-transfer (bash)
    required: false
  ssh_host:
    description: SSH hostname
    required: true
  ssh_port:
    description: SSH port number
    required: false
    default: '22'
  ssh_user:
    description: SSH user
    required: true
  ssh_private_key:
    description: SSH private key
    required: true
  scratch:
    description: Write all paths from scratch
    required: false
  exclude_paths:
    description: Paths to exclude from transfer, as accepted by rsync --exclude
    required: false
  include_paths:
    description: Paths to include in transfer, as accepted by rsync --include
    required: false
runs:
  using: composite
  steps:
    - name: "Create remote directory '${{ inputs.remote_dir }}' if it doesn't exist"
      env:
        COMMANDS: |
          cd /
          mkdir -p ${{ inputs.remote_dir }}; true
      uses: esign/.github/.github/actions/execute@v2
      with:
        host: ${{ inputs.ssh_host }}
        port: ${{ inputs.ssh_port }}
        user: ${{ inputs.ssh_user }}
        commands: ${{ env.COMMANDS }}
    - id: compose-rsync-flags
      name: "Compose rsync flags"
      shell: bash
      run: |
        excludes=$(echo "${{ inputs.exclude_paths }}" | sed -r '1,$s/^(.+)$/--exclude \1/' | sed -z '1,$s/\n/ /g')
        echo "$excludes"
        includes=$(echo "${{ inputs.include_paths }}" | sed -r '1,$s/^(.+)$/--include \1/' | sed -z '1,$s/\n/ /g')
        echo "$includes"
        flags="$excludes"
        echo "$flags"
        
        if [ ! -z "$includes" ]
        then
          flags="$flags $includes"
          echo "$flags"
        fi

        flags="$flags --include \"*/\""
        echo "$flags"
        
        if [ "${{ inputs.scratch }}" = false ]
        then
          flags="$flags --exclude \"*\""
          echo "$flags"
        fi
        
        echo "flags=$flags" >> $GITHUB_OUTPUT