name: Environment Deployment

on:
  workflow_dispatch:
    inputs:
      github_sha:
        description: 'Commit SHA to be deployed'
        required: false
        type: string

jobs:
  deployment:
    uses: esign/.github/.github/workflows/deployment.yml@v1
    with:
      branch:
      github_sha: ${{ github.event.inputs.github_sha }}
      ssh_host: ${{ vars.ENVIRONMENT_SSH_USER }}
      ssh_user: ${{ vars.ENVIRONMENT_SSH_USER }}
      known_hosts: ${{ secrets.ENVIRONMENT_KNOWN_HOSTS }}
      remote_dir:
      local_dir: '.'
      exclude_paths: |
        vendor
        node_modules
        resources/cache
        *.git*
      post_deploy_commands: |
        bash post_deployment_environment.sh
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.ENVIRONMENT_SSH_PRIVATE_KEY }}
