name: Deployment

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      github_sha:
        required: false
        type: string
      artifact:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch ${{ inputs.branch }}
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0
      - name: Determine commit SHA
        run: |
          if [ ! -z "${{ inputs.github_sha }}" ]
          then
            echo "deploy_sha=${{ inputs.github_sha }}" >> $GITHUB_ENV
          else
            echo "deploy_sha=${{ github.sha }}" >> $GITHUB_ENV
          fi
      - name: "Checkout ${{ inputs.branch }} at commit ${{ env.deploy_sha }}"
        run: |
          git checkout ${{ env.deploy_sha }}
      - name: Log revision
        run: |
          commit_short_sha=$(git rev-parse --short HEAD)
          commit_msg=$(git log -1 --pretty=%B)
          echo "::notice::commit $commit_short_sha $commit_sha"
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact }}
          path: .
