name: Deployment

on:
  workflow_call:
    inputs:
      artifact:
        required: true
        type: string

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete build artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: ${{ inputs.artifact }}
