name: Deployment

on:
  workflow_call:
    inputs:
      remote_project_folder:
        required: true
        type: string
      post_deploy_commands:
        required: false
        type: string
      ssh_host:
        required: true
        type: string
      ssh_user:
        required: true
        type: string
      path_in_repository:
        required: false
        type: string
        default: '.'
      artifact:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      KNOWN_HOSTS:
        required: true

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: "Create remote folder '${{ inputs.remote_project_folder }}' if it doesn't exist"
        env:
          COMMANDS: |
            cd /\
            mkdir -p ${{ inputs.remote_project_folder }}; true
        uses: esign/.github/.github/actions/execute@v1
        with:
          host: ${{ inputs.ssh_host }}
          user: ${{ inputs.ssh_user }}
          commands: ${{ env.COMMANDS }}
      - name: "Upload local '${{ inputs.path_in_repository }}' to remote '${{ inputs.remote_project_folder }}'"
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -azr --exclude '*.git*' --exclude "vendor" --exclude "node_modules" --exclude "resources/cache" --delete
          path: ${{ inputs.path_in_repository }}
          remote_path: ${{ inputs.remote_project_folder }}
          remote_host: ${{ inputs.ssh_host }}
          remote_user: ${{ inputs.ssh_user }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Execute post deploy commands
        env:
          COMMANDS: |
            cd "${{ inputs.remote_project_folder }}"\
            ${{ inputs.post_deploy_commands }}
        uses: esign/.github/.github/actions/execute@v1
        with:
          host: ${{ inputs.ssh_host }}
          user: ${{ inputs.ssh_user }}
          commands: ${{ env.COMMANDS }}

