name: Deployment

on:
  workflow_call:
    inputs:
      branch:
        description: Branch to check out
        required: true
        type: string
      github_sha:
        description: SHA of commit to check out (defaults to latest)
        required: false
        type: string
      remote_dir:
        description: Path to the directory on the remote to transfer files to
        required: true
        type: string
      local_dir:
        description: Path to the local directory to transfer files from
        required: false
        type: string
        default: '.'
      exclude_paths:
        description: Paths to exclude from transfer, as accepted by rsync --exclude
        required: false
        type: string
      post_deploy_commands:
        description: Commands to execute post-deployment (bash)
        required: true
        type: string
      ssh_host:
        description: SSH hostname
        required: true
        type: string
      ssh_port:
        description: SSH port number
        required: false
        type: number
        default: 22
      ssh_user:
        description: SSH user
        required: true
        type: string
      known_hosts:
        description: SSH hosts to trust
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Determine commit SHA
        shell: bash
        run: |
          if [ ! -z "${{ inputs.github_sha }}" ]
          then
            echo "deploy_sha=${{ inputs.github_sha }}" >> $GITHUB_ENV
            echo "fetch_depth=0" >> $GITHUB_ENV
          else
            echo "deploy_sha=${{ github.sha }}" >> $GITHUB_ENV
            echo "fetch_depth=1" >> $GITHUB_ENV
          fi
      - name: Checkout
        uses: esign/.github/.github/actions/checkout@v1
        with:
          branch: ${{ inputs.branch }}
          github_sha: ${{ env.deploy_sha }}
      - name: Log revision
        uses: esign/.github/.github/actions/log-revision@v1
      - name: Transfer
        uses: esign/.github/.github/actions/transfer@v1.1.8
        with:
          remote_dir: ${{ inputs.remote_dir }}
          local_dir: ${{ inputs.local_dir }}
          post_transfer_commands: ${{ inputs.post_deploy_commands }}
          ssh_host: ${{ inputs.ssh_host }}
          ssh_port: ${{ inputs.ssh_port }}
          ssh_user: ${{ inputs.ssh_user }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_known_hosts: ${{ inputs.known_hosts }}
          exclude_paths: ${{ inputs.exclude_paths }}
